<?php

namespace SoftUniBlogBundle\Repository;

/**
 * delRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class delRepository extends \Doctrine\ORM\EntityRepository
{
}
